apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: alex-resume-website-ingress
  namespace: alex-resume-website
spec:
  ingressClassName: nginx
  rules:
    - host: home.alexkurata.com
      http:
        paths:
          - backend:
              service:
                name: resume
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - alexkurata.com
      secretName: alex-resume-tls
