apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: resume-git-event
spec:
  serviceAccountName: pipeline-account
  triggers:
  - name: github-listener
    interceptors:
    - params:
      - name: secretRef
        value: null
      - name: eventTypes
        value:
          - push
          - pull_request
      ref:
        kind: ClusterInterceptor
        name: github
    template:
      spec:
        resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: resume-build-pipelinerun-
          spec:
            pipelineRef:
              name: build-and-deploy-pipeline
            params:
              - name: gitUrl
                value: ssh://git@github.com:Akurata/resume-website.git
              - name: deploymentName
                value: resume
              - name: namespace
                value: alex-resume-website
              - name: imageUrl
                value: registry.alexkurata.com/akurata/alex-resume-website
              - name: imageTag
                value: latest
            serviceAccountName: pipeline-account
            workspaces:
              - name: git-source
                volumeClaimTemplate:
                  metadata:
                    name: resume-build-pvc
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
secrets:
- name: github-ssh-key
- name: kube-api-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: pipeline-account
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: pipeline-account